"use client";

import { useRef } from "react";
import { motion, useScroll, useTransform } from "framer-motion";

const PHASES = [
  {
    phase: "01",
    title: "THE LANDING 🦩",
    description: "7,777 Flamingos arrive on Robinhood Chain.\n\nThe beginning of the flock — collection launch, community building, collaborations and exclusive allowlist opportunities across the Robinhood ecosystem.",
  },
  {
    phase: "02",
    title: "FLOCK STAKING 💰",
    description: "Your Flamingo can work for you.\n\nStake your Flamingo and earn a share of the creator fees generated by secondary sales of the collection.\n\nThe longer-term goal: turn holding a Flamingo into an active part of the ecosystem rather than simply owning a PFP.\n\nHold → Stake → Earn",
  },
  {
    phase: "03",
    title: "FLAMINGO EVOLUTION 🎮",
    description: "Your Flamingo. Your journey. Your evolution.\n\nA dedicated Flamingo game where your NFT becomes your playable character.\n\nPlay, complete challenges, level up your Flamingo and unlock new evolutionary forms, abilities and experiences.\n\nDifferent Flamingos can progress differently depending on gameplay and achievements.\n\nPlay → Level Up → Evolve",
  },
  {
    phase: "04",
    title: "THE FLOCK PASS 🎟️",
    description: "Your Flamingo is your passport to the Flock.\n\nHolding a Flamingo unlocks access to the wider ecosystem:\n\n• Exclusive NFT drops\n• Partner allowlists\n• Flamingo game experiences\n• Holder-only rewards\n• Exclusive community events\n• Early access to future Flamingo experiences\n\nThe goal is simple:\nOne Flamingo → An entire ecosystem.",
  },
];

export function Roadmap() {
  const containerRef = useRef<HTMLDivElement>(null);
  
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start center", "end center"]
  });

  const lineHeight = useTransform(scrollYProgress, [0, 1], ["0%", "100%"]);

  return (
    <section ref={containerRef} className="relative w-full py-32 bg-[#020202] overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 relative z-10">
        
        <div className="text-center mb-24">
          <h2 className="text-5xl md:text-7xl font-display font-black tracking-tighter uppercase text-white">
            The Flock Takes <span className="text-brand-pink">Flight</span>
          </h2>
        </div>

        <div className="relative">
          {/* Main vertical line */}
          <div className="absolute left-4 md:left-1/2 top-0 bottom-0 w-1 bg-white/10 -translate-x-1/2 rounded-full" />
          
          {/* Animated fill line */}
          <motion.div 
            style={{ height: lineHeight }}
            className="absolute left-4 md:left-1/2 top-0 w-1 bg-gradient-to-b from-brand-pink to-brand-cyan -translate-x-1/2 rounded-full shadow-[0_0_15px_#ff1493]"
          />

          <div className="flex flex-col gap-16 md:gap-24">
            {PHASES.map((phase, index) => {
              const isEven = index % 2 === 0;
              return (
                <div key={index} className="relative flex items-center md:justify-between w-full">
                  
                  {/* Node */}
                  <div className="absolute left-4 md:left-1/2 w-6 h-6 rounded-full bg-[#020202] border-4 border-brand-pink -translate-x-1/2 z-10 shadow-[0_0_10px_#ff1493]" />
                  
                  {/* Content Container */}
                  <motion.div
                    initial={{ opacity: 0, x: isEven ? -50 : 50 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6, type: "spring" }}
                    className={`ml-16 md:ml-0 w-[calc(100%-4rem)] md:w-[45%] ${isEven ? "md:text-right" : "md:ml-auto md:text-left"}`}
                  >
                    <div className="p-8 rounded-2xl bg-white/5 border border-white/10 hover:border-brand-pink/50 transition-colors duration-300">
                      <span className="text-brand-cyan font-mono text-sm tracking-widest mb-2 block">
                        {phase.phase}
                      </span>
                      <h3 className="text-3xl font-display font-bold text-white uppercase mb-3">
                        {phase.title}
                      </h3>
                      <p className="text-white/60 font-sans font-light whitespace-pre-line">
                        {phase.description}
                      </p>
                    </div>
                  </motion.div>
                </div>
              );
            })}
          </div>
          
          {/* Overall Roadmap Summary */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="mt-32 p-8 md:p-12 rounded-3xl bg-gradient-to-br from-brand-pink/20 to-brand-cyan/20 border border-white/20 text-center relative overflow-hidden"
          >
            <div className="absolute inset-0 bg-noise opacity-50 mix-blend-overlay pointer-events-none" />
            <h3 className="text-2xl font-display font-bold text-white uppercase mb-6 flex items-center justify-center gap-3">
              <span className="text-3xl">🔥</span> Overall Roadmap
            </h3>
            <div className="text-3xl md:text-5xl font-display font-black text-transparent bg-clip-text bg-gradient-to-r from-white via-brand-pink to-brand-cyan uppercase tracking-tighter mb-6">
              MINT → STAKE → EVOLVE → UNLOCK
            </div>
            <p className="text-lg text-white/80 font-sans font-light max-w-2xl mx-auto">
              That gives you four very different reasons to care: ownership, earning, gameplay, and access.
            </p>
          </motion.div>

        </div>

      </div>
    </section>
  );
}
